### PR TITLE
Link block to explorer

### PR DESCRIPTION
**Pull request by rromanchuk**

### CODE REVIEW

**Comment by Har01d** [comment]
That doesn't seem to work because the database doesn't store block hashes. At the same time Insight API doesn't accept block heights as an input. I can either rewrite the code to support Insight API or I can just use another service like https://www.blocktrail.com/tBTC/block/{height} or http://tbtc.blockr.io/block/info/{height} for this purpose. What would be preferable?

**Comment by Har01d** [comment]
As it turns out, I was wrong. Insight API does support block height as an input: `/insight-api/block-index/[:height]`

**Comment by Har01d** [comment]
@rromanchuk, see https://github.com/Har01d/XTTestnetBlocks/commit/686a31467707aa37ad979fc715f8a188dd5f69a0

**Comment by rromanchuk** [comment]
ahh, cool. I did that blindly hoping for the best.

**Pull request closed without merging**
